### ISSUE TITLE
`github.com/hhatto/gorst` needs its license reviewed. Action required.

### ISSUE THREAD

**Issue by dangoor** [github/depstubber#20]
# Dependency license policy warning 🚨

ℹ️ The OSPO policy service scans our projects for upstream packages we depend on whose licenses are legally risky and marks them for further review.

The project's  `go.sum` pulls in `github.com/hhatto/gorst` at version `v0.0.0-20181029133204-ca9f730cac5b`. According to [ClearlyDefined](https://clearlydefined.io), that package has the license `BSD-3-Clause AND GPL-2.0-or-later AND MIT`, which requires further review. See the approved [policy list here](https://github.com/github/licensecheck-data/blob/main/license-policy.yaml).

To find license information you may want to [check the source](https://pkg.go.dev/github.com/hhatto/gorst@v0.0.0-20181029133204-ca9f730cac5b).
You can also check the [registry](https://pkg.go.dev/github.com/hhatto/gorst@v0.0.0-20181029133204-ca9f730cac5b)

## How to resolve this issue 🔧

Don't worry, we've got you covered! [Head over to the documentation on The Hub](https://thehub.github.com/epd/engineering/products-and-services/dotcom/license-compliance/) for information on how to address this and maybe even make the open source world a better place in the process. :superhero:

We've also got a bot to help you with common fixes, so keep an eye out for comments below! :robot:

**Comment by dangoor** [comment]
Hi @owen-mc! (This issue was created by a program, but this comment is actually me)

I would love a few minutes of your time on this. If you can read the issue description and look at related docs and see if what you need to do becomes clear, I'd appreciate it. Feel free to grab me in Slack with any questions or comments. I'm very interested in making it as frictionless as can be to resolve any license issues. If you find it taking more than a few minutes, please do reach out in Slack because that is useful information.

**Comment by owen-mc** [comment]
/exception This repo is not linked into any GitHub code. It is a standalone program that is used by people contributing to [our open source CodeQL Go libraries](https://github.com/github/codeql/) to help them write tests. Note: this repo is public and open-source.

**Comment by dangoor** [comment]
Closing this issue because the problem has been addressed.
