### ISSUE TITLE
Field missing from struct

### ISSUE THREAD

**Issue by owen-mc** [github/depstubber#6]
The stub made by depstubber for `Token struct` in `golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d` is missing the last field Raw interface{} :
https://github.com/github/codeql-go/pull/259/files#diff-2de83b6364a4409b095b7784efcfb945R54
https://github.com/golang/oauth2/blob/bf48bf16ab8d622ce64ec6ce98d2c98f916b6303/internal/token.go#L33

**Comment by gagliardetto** [comment]
I believe the `Token` that was stubbed by depstubber is from here:

https://github.com/golang/oauth2/blob/bf48bf16ab8d622ce64ec6ce98d2c98f916b6303/token.go#L31-L55

**Comment by gagliardetto** [comment]
(notice that the `raw` field is unexported here, but it is exported `Raw` in [/internal/token.go](https://github.com/golang/oauth2/blob/bf48bf16ab8d622ce64ec6ce98d2c98f916b6303/internal/token.go#L33))

`depstubber` cannot stub unexported fields.

**Comment by owen-mc** [comment]
Ah, that makes sense. My mistake.

**Comment by sauyon** [comment]
> `depstubber` cannot stub unexported fields.

At some point I should really do this with a parser and not reflect...

**Comment by gagliardetto** [comment]
> At some point I should really do this with a parser and not reflect...

I built a tool that's similar to depstubber (it's a prototype at this stage) that works with AST instead of reflection. Go code parsing stuff is interesting and hard. It gave me a wider and deeper understanding of what codeql deals with.

Maybe I'll complete it in the next few months/weeks.
